apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: rating
  mainReadySeconds: 10
  stategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavilable: 0
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - name: rating
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}
        env:
        - name: DB_DATABASE
          value: "bookrating"
        ports:
        - containerPort: 80
