apiVersion: v1
kind: Service
metadata:
  name: {{ template "rating.database" . }}
  labels:
{{ include "rating.labels" . | indent 4 }}
spec:
  ports:
    - port: 5432
      name: tcp-database
  selector:
{{ include "rating.matchLabels" . | indent 4 }}
    app: database
    version: {{ .Values.database.image.tag }}
  clusterIP: None