apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - image: docker.io/tmaxcloudck/bookinfo-order:latest
        name: order
        envFrom:
        - configMapRef:
            name: config-dev
        env:
        - name: BOOK_PAYMENT_URL
          value: "http://payment:8080"
        - name: DB_DATABASE
          value: "bookorder"
        ports:
        - containerPort: 80
