apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}
        env:
        - name: BOOK_PAYMENT_URL
          value: "http://payment:8080"
        - name: DB_DATABASE
          value: "bookorder"
        ports:
        - containerPort: 80
