apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "bookinfo.istio.ingressVirtualService" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
spec:
  hosts:
    - {{ .Values.externalDomain }}
  gateways:
    - {{ template "bookinfo.istio.ingressGateway" . }}
  http:
    - name: core
      match:
        - uri:
            prefix: /api/books
      route:
        - destination:
            host: {{ .Values.upstream.core.host }}
            port:
              number: {{ .Values.upstream.core.port }}
    - name: rating
      match:
        - uri:
            prefix: /api/rating
      route:
        - destination:
            host: {{ .Values.upstream.rating.host }}
            port:
              number: {{ .Values.upstream.rating.port }}
    - name: orders
      match:
        - uri:
            prefix: /api/orders
      route:
        - destination:
            host: {{ .Values.upstream.order.host }}
            port:
              number: {{ .Values.upstream.order.port }}
