{{- if eq .Values.eventing.type "internal" -}}
apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: {{ template "bookinfo.kafka.templateInstance" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
spec:
  clustertemplate:
    metadata:
      name: {{ template "bookinfo.kafka.template" . }}
    parameters:
    - name: APP_NAME
      value: {{ template "bookinfo.fullname" . }}
    - name: IS_EXTERNAL
      value: "true"
    - name: KAFKA_STORAGE
      value: {{ .Values.persistence.persistentVolumeClaim.kafka.size }}
    - name: STORAGE_CLASS
      value: {{ .Values.persistence.persistentVolumeClaim.kafka.storageClass }}
    - name: KAFKA_RESOURCE_CPU
      value: {{ .Values.eventing.internal.kafka.resources.requests.cpu }}
    - name: KAFKA_RESOURCE_MEM
      value: {{ .Values.eventing.internal.kafka.resources.requests.memory }}
    - name: ZOOKEEPER_RESOURCE_CPU
      value: {{ .Values.eventing.internal.zookeeper.resources.requests.cpu }}
    - name: ZOOKEEPER_RESOURCE_MEM
      value: {{ .Values.eventing.internal.zookeeper.resources.requests.cpu }}
    - name: DEFAULT_TOPIC
      value: tmax
{{- end -}}