{{- if eq .Values.eventing.type "internal" -}}
apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: {{ template "bookinfo.kafka.templateInstance" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: {{ template "bookinfo.kafka.template" . }}
    parameters:
    - name: APP_NAME
      value: {{ template "bookinfo.fullname" . }}
    - name: KAFKA_STORAGE
      value: {{ .Values.persistence.persistentVolumeClaim.kafka.size }}
    - name: STORAGE_CLASS
      value: {{ .Values.persistence.persistentVolumeClaim.kafka.storageClass }}
    - name: KAFKA_RES_REQ_CPU
      value: {{ .Values.eventing.internal.kafka.resources.requests.cpu }}
    - name: KAFKA_RES_REQ_MEM
      value: {{ .Values.eventing.internal.kafka.resources.requests.memory }}
    - name: KAFKA_RES_LIMIT_CPU
      value: {{ .Values.eventing.internal.kafka.resources.limits.cpu }}
    - name: KAFKA_RES_LIMIT_MEM
      value: {{ .Values.eventing.internal.kafka.resources.limits.memory }}
    - name: ZOOKEEPER_RES_REQ_CPU
      value: {{ .Values.eventing.internal.zookeeper.resources.requests.cpu }}
    - name: ZOOKEEPER_RES_REQ_MEM
      value: {{ .Values.eventing.internal.zookeeper.resources.requests.memory }}
    - name: ZOOKEEPER_RES_LIMIT_CPU
      value: {{ .Values.eventing.internal.zookeeper.resources.limits.cpu }}
    - name: ZOOKEEPER_RES_LIMIT_MEM
      value: {{ .Values.eventing.internal.zookeeper.resources.limits.memory }}
{{- end -}}