apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - image: docker.io/tmaxcloudck/bookinfo-rating:latest
        name: rating
        envFrom:
        - configMapRef:
            name: config-dev
        env:
        - name: DB_DATABASE
          value: "bookrating"
        ports:
        - containerPort: 80
