apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy:
    canary:
      maxSurge: "20%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
          - configMapRef:
              name: {{ .Values.configMap.name }}
          env:
          - name: BOOK_PAYMENT_URL
            value: "http://payment:8080"
          - name: DB_DATABASE
            value: "bookorder"
          ports:
            - containerPort: 80
