apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.appName }}
