# Default values for helm-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

externalDomain: bookinfo.192.168.0.102.nip.io

upstream:
  core:
    host: core-helm-core-rollouts-core
    port: 8080
  rating:
    host: rating-helm-rating-rollouts-rating
    port: 8080
  order:
    host: order-helm-order-rollouts-order
    port: 8080
  payment:
    host: "192.168.9.71.nip.io"

istio:
  ingressGateway:
    selector:
      key: app
      value: istio-ingressgateway
  egressGateway:
    selector:
      key: app
      value: istio-egressgateway
    hostname: istio-egressgateway.istio-system.svc.cluster.local