apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "core.app" . }}
  labels:
{{ include "core.labels" . | indent 4 }}
spec:
  hosts:
    - {{ template "core.app" . }}-stable
  http:
    - name: core
      match:
        - uri:
            prefix: /api/books
      route:
        - destination:
            host: {{ template "core.app" . }}-stable
            port:
              number: 8080
          weight: 100
        - destination:
            host: {{ template "core.app" . }}-canary
            port:
              number: 8080
          weight: 0