apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "core.app" . }}
  labels:
{{ include "core.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.core.replicas }}
  revisionHistoryLimit: {{ .Values.core.revisionHistoryLimit }}
  selector:
    matchLabels:
{{ include "core.matchLabels" . | indent 6 }}
      app: {{ template "core.app" . }}
  strategy:
    canary:
      canaryService: {{ template "core.app" . }}-canary
      stableService: {{ template "core.app" . }}-stable
      trafficRouting:
        istio:
          virtualService:
            name: {{ template "core.app" . }}
            routes:
              - core
      steps:
        - setWeight: {{ .Values.core.rolloutPolicy.canary.ratio }}
        - pause:
            duration: {{ .Values.core.rolloutPolicy.canary.pause.duration }}
  template:
    metadata:
      labels:
{{ include "core.matchLabels" . | indent 8 }}
        app: {{ template "core.app" . }}
    spec:
      containers:
        - name: core
          image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ template "core.app" . }}
          ports:
            - containerPort: {{ template "core.app.containerPort" . }}
          volumeMounts:
            - name: conf
              mountPath: /app/application.properties
              subPath: application.properties
      volumes:
        - name: conf
          configMap:
            name: {{ template "core.app" . }}
            items:
              - key: application.properties
                path: application.properties