apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: helm-order-rollouts
    repoURL: https://github.com/tmax-cloud/bookinfo-deployment.git
    targetRevision: app-of-apps