apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy:
    blueGreen:
      activeService: {{ .Values.appName }}
      previewService: {{ .Values.appName }}-preview
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
          - configMapRef:
              name: {{ .Values.configMap.name }}
          env:
          - name: BOOK_RATING_URL
            value: "http://rating:8080"
          - name: DB_DATABASE
            value: "bookcore"
          ports:
            - containerPort: 80
