# Default values for helm-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appName: core-blue-green

replicaCount: 2

revisionHistoryLimit: 3

image:
  repository: core.hr.172.22.11.16.nip.io/shinhan-bookinfo/bookinfo-core
  tag: blue

service:
  port: 8080
  targetPort: 8080

configMap:
  name: config-ops
