apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bookinfo.database" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "bookinfo.matchLabels" . | indent 6 }}
      component: database
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
{{ include "bookinfo.matchLabels" . | indent 8 }}
        component: database
    spec:
      containers:
        - name: database
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          