# Default values for helm-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

externalDomain: bookinfo.172.22.11.21.nip.io

upstream:
  paymentURL: "http://192.168.9.71.nip.io"

istio:
  ingressGateway:
    selector:
      key: app
      value: istio-ingressgateway

core:
  image:
    repository: core.hr.172.22.11.16.nip.io/shinhan-bookinfo/bookinfo-core
    tag: v0.0.5
  revisionHistoryLimit: 3
  serviceAccountName: ""
  replicas: 1

rating:
  image:
    repository: core.hr.172.22.11.16.nip.io/shinhan-bookinfo/bookinfo-rating
    tag: v0.0.5
  revisionHistoryLimit: 3
  serviceAccountName: ""
  replicas: 1
  rolloutPolicy:
    canary:
      ratio: 50

order:
  image:
    repository: core.hr.172.22.11.16.nip.io/shinhan-bookinfo/bookinfo-order
    tag: v0.0.5
  revisionHistoryLimit: 3
  serviceAccountName: ""
  replicas: 1

database:
  image:
    repository: core.hr.172.22.11.16.nip.io/shinhan-bookinfo/bookinfo-db
    tag: v0.0.5
  nodeSelector: {}
  tolerations: []
  affinity: {}


kafka:
  bootstrapServers: "bookinfo-kafka:9092"
  groupId: "book"

trace:
  jaeger:
    httpSenderURL: "http://jaeger-collector.istio-system:14268/api/traces"

persistence:
  enabled: true
  # Setting it to "keep" to avoid removing PVCs during a helm delete
  # operation. Leaving it empty will delete PVCs after the chart deleted
  # (this does not apply for PVCs that are created for internal database
  # and redis components, i.e. they are never deleted automatically)
  resourcePolicy: "keep"
  persistentVolumeClaim:
    database:
      existingClaim: ""
      storageClass: "csi-cephfs-sc"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    kafka:
      existingClaim: ""
      storageClass: "csi-cephfs-sc"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi