apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "bookinfo.rating.virtualservice" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
spec:
  hosts:
    - {{ template "bookinfo.rating" . }}
  http:
    - name: rating
      match:
        - uri:
            prefix: /api/rating
      route:
        - destination:
            host: {{ template "bookinfo.rating" . }}
            port:
              number: 8080
          weight: 100
        - destination:
            host: {{ template "bookinfo.rating" . }}-canary
            port:
              number: 8080
          weight: 0