apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "rating.app" . }}
  labels:
{{ include "rating.labels" . | indent 4 }}
spec:
  hosts:
    - {{ template "rating.app" . }}
  http:
    - name: rating
      match:
        - uri:
            prefix: /api/rating
      route:
        - destination:
            host: {{ template "rating.app" . }}-stable
            port:
              number: 8080
          weight: 100
        - destination:
            host: {{ template "rating.app" . }}-canary
            port:
              number: 8080
          weight: 0