apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-payment
spec:
  hosts:
  - {{ .Values.upstream.payment }}
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 8080
    protocol: HTTP
  resolution: DNS